---
driver:
  name: docker
  use_sudo: false

platforms:
- name: centos-6
- name: debian-6
  run_list: recipe[apt]
- name: debian-7
  run_list: recipe[apt]
- name: ubuntu-10.04
  run_list: recipe[apt]
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-14.10
  run_list: recipe[apt]
